name: reusable workflow
on: 
  workflow_call:   
    input:
      node-version:
        type:string
        requiered:true
        default:'lts/*'
        
jobs:
  run-npm-test:
    runs-on: ubuntu-latest
    steps:
        - name: checkout
          uses: actions/checkout@v3
        - name : setup node
          uses: actions/setup-node@v3
          with:
            node-version: 'lts/*'
        - name: run test
          shell: bash
          run: |
            node -v
            npm install
            npm test